/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // High-Density Terminal — Bloomberg dark theme (Material Design 3 dark)
        'primary': '#ffc56c',
        'on-primary': '#442c00',
        'primary-container': '#f0a500',
        'on-primary-container': '#5f3f00',
        'primary-fixed': '#ffddaf',
        'primary-fixed-dim': '#ffba44',
        'on-primary-fixed': '#281800',
        'on-primary-fixed-variant': '#614000',
        'inverse-primary': '#805600',
        'secondary': '#acc7ff',
        'on-secondary': '#002e68',
        'secondary-container': '#056ee3',
        'on-secondary-container': '#f8f8ff',
        'secondary-fixed': '#d7e2ff',
        'secondary-fixed-dim': '#acc7ff',
        'on-secondary-fixed': '#001a40',
        'on-secondary-fixed-variant': '#004492',
        'tertiary': '#84e588',
        'on-tertiary': '#00390e',
        'tertiary-container': '#68c86f',
        'on-tertiary-container': '#005218',
        'tertiary-fixed': '#97f999',
        'tertiary-fixed-dim': '#7bdb80',
        'on-tertiary-fixed': '#002106',
        'on-tertiary-fixed-variant': '#005319',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'surface': '#10141a',
        'surface-dim': '#10141a',
        'surface-bright': '#353940',
        'surface-container-lowest': '#0a0e14',
        'surface-container-low': '#181c22',
        'surface-container': '#1c2026',
        'surface-container-high': '#262a31',
        'surface-container-highest': '#31353c',
        'on-surface': '#dfe2eb',
        'on-surface-variant': '#d6c4ac',
        'inverse-surface': '#dfe2eb',
        'inverse-on-surface': '#2d3137',
        'outline': '#9f8e79',
        'outline-variant': '#514533',
        'surface-tint': '#ffba44',
        'surface-variant': '#31353c',
        'background': '#10141a',
        'on-background': '#dfe2eb',
        // Terminal specific (legacy term tokens)
        'terminal-bg': '#0d1117',
        'terminal-card': '#161b22',
        'terminal-border': '#30363d',
        'terminal-text': '#e6edf3',
        'terminal-muted': '#8b949e',
        'terminal-accent': '#f0a500',
        // Financial market indicators
        'market-up': '#84e588',
        'market-down': '#ffb4ab',
        'gain': '#84e588',
        'loss': '#ffb4ab',
        // Sơn mài (Vietnamese lacquer) theme — opt in via BaseLayout theme="lacquer"
        'lacquer': {
          DEFAULT: '#1A0D0B',
          deep: '#120807',
          raised: '#26130F',
        },
        'cinnabar': {
          DEFAULT: '#B8321C',
          deep: '#962615',
          soft: '#E07A5F',
        },
        'gold': {
          DEFAULT: '#C8A15A',
          soft: '#E0C285',
          dim: '#8C7140',
        },
        'eggshell': {
          DEFAULT: '#EFE6D6',
          muted: '#BFAF9A',
        },
        'ash': '#A08C78',
        'jade': '#8DBF9F',
      },
      keyframes: {
        rise: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        // Seal pressed onto the page; ends on the seal's resting -5deg tilt
        stamp: {
          '0%': { opacity: '0', transform: 'scale(1.4) rotate(-16deg)' },
          '55%': { opacity: '1', transform: 'scale(0.92) rotate(-3deg)' },
          '100%': { opacity: '1', transform: 'scale(1) rotate(-5deg)' },
        },
      },
      animation: {
        rise: 'rise 0.9s cubic-bezier(0.2, 0.8, 0.2, 1) both',
        stamp: 'stamp 0.55s cubic-bezier(0.2, 0.8, 0.2, 1) both',
      },
      // Sharp corners — 0px everywhere except full
      borderRadius: {
        'none': '0px',
        DEFAULT: '0px',
        'sm': '0px',
        'md': '0px',
        'lg': '0px',
        'xl': '0px',
        '2xl': '0px',
        '3xl': '0px',
        'full': '9999px',
      },
      spacing: {
        'section-gap': '80px',
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        'unit': '4px',
        'gutter': '24px',
        'container-max': '1200px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'base': '4px',
        'margin': '16px',
      },
      fontFamily: {
        'headline-lg': ['JetBrains Mono', 'ui-monospace', 'monospace'],
        'display-xl-mobile': ['JetBrains Mono', 'ui-monospace', 'monospace'],
        'headline-md': ['JetBrains Mono', 'ui-monospace', 'monospace'],
        'display-xl': ['JetBrains Mono', 'ui-monospace', 'monospace'],
        'headline-sm': ['JetBrains Mono', 'ui-monospace', 'monospace'],
        'display-lg': ['JetBrains Mono', 'ui-monospace', 'monospace'],
        'body-lg': ['Inter', 'ui-sans-serif', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'ui-monospace', 'monospace'],
        'label-md': ['JetBrains Mono', 'ui-monospace', 'monospace'],
        'label-lg': ['JetBrains Mono', 'ui-monospace', 'monospace'],
        'label-data': ['JetBrains Mono', 'ui-monospace', 'monospace'],
        'mono-data': ['JetBrains Mono', 'ui-monospace', 'monospace'],
        'body-sm': ['Inter', 'ui-sans-serif', 'sans-serif'],
        'body-md': ['Inter', 'ui-sans-serif', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
        sans: ['Inter', 'ui-sans-serif', 'sans-serif'],
        'lacquer-display': ['"Cormorant Garamond"', 'Georgia', 'serif'],
        'lacquer-body': ['"Be Vietnam Pro"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-xl-mobile': ['36px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
        'label-md': ['11px', { lineHeight: '1.1', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-lg': ['13px', { lineHeight: '1.2', fontWeight: '500' }],
        'label-data': ['13px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
        'mono-data': ['14px', { lineHeight: '1.2', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'lacquer-hero': ['clamp(3rem, 8vw, 6.5rem)', { lineHeight: '0.95', fontWeight: '600' }],
        'lacquer-h2': ['clamp(2.5rem, 5vw, 3.75rem)', { lineHeight: '1', fontWeight: '600' }],
        'lacquer-h3': ['1.625rem', { lineHeight: '1.15', fontWeight: '600' }],
        'lacquer-figure': ['3rem', { lineHeight: '1', fontWeight: '600' }],
        'lacquer-lead': ['1.125rem', { lineHeight: '1.7', fontWeight: '400' }],
        'lacquer-body': ['1rem', { lineHeight: '1.75', fontWeight: '400' }],
        'lacquer-small': ['0.875rem', { lineHeight: '1.6', fontWeight: '400' }],
        'lacquer-eyebrow': ['0.6875rem', { lineHeight: '1.4', letterSpacing: '0.2em', fontWeight: '500' }],
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
